alert:
- debug
description: Detects Obfuscated Powershell via Stdin in Scripts
filter:
- query:
    query_string:
      query: (winlog.channel:"Security" AND winlog.event_data.ServiceFileName.keyword:/(?i).*(set).*&&\s?set.*(environment|invoke|\${?input).*&&.*"/ AND event.code:"4697")
index: winlogbeat-*
name: 80b708f3-d034-40e4-a6c8-d23b7a7db3d1-Invoke-Obfuscation-Via-Stdin
priority: 2
realert:
  minutes: 0
type: any

import: /rules/Windows-All.config
