alert:
- debug
description: Detects Obfuscated use of Environment Variables to execute PowerShell
filter:
- query:
    query_string:
      query: (winlog.channel:"Security" AND event.code:"4697" AND winlog.event_data.ServiceFileName.keyword:/.*cmd.{0,5}(?:\/c|\/r)(?:\s|)\"set\s[a-zA-Z]{3,6}.*(?:\{\d\}){1,}\\\"\s+?\-f(?:.*\)){1,}.*\"/)
index: winlogbeat-*
name: dcf2db1f-f091-425b-a821-c05875b8925a-Invoke-Obfuscation-VAR+-Launcher
priority: 2
realert:
  minutes: 0
type: any

