alert:
- debug
description: Modifications to a config that will serve an adversary's impacts or persistence
filter:
- query:
    query_string:
      query: \*.keyword:(*ip\ http\ server* OR *ip\ https\ server* OR *kron\ policy\-list* OR *kron\ occurrence* OR *policy\-list* OR *access\-list* OR *ip\ access\-group* OR *archive\ maximum*)
index: filebeat-10*
name: 671ffc77-50a7-464f-9e3d-9ea2b493b26b-Cisco-Modify-Configuration
priority: 3
realert:
  minutes: 0
type: any

import: Network-All.conf
